### ISSUE TITLE
Regarding the issue of TG-Bot limit of 20 messages per minute in groups/channels (and more pictures count as more messages)

### ISSUE THREAD

**Issue by SagiriShiho** [y-young/nazurin#6]
-problem
"Also note that your bot will not be able to send more than 20 messages per minute to the same group."
https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

Due to official restrictions, TG-Bot limits 20 messages per minute in groups/channels (and multiple pictures count as more information)
So when the limit is reached, there will be a failure to publish

2020-11-20T22:22:20.886923+00:00 app[web.1]: 2020-11-20 22:22:20,886-bot-INFO-BadRequest exception: Group send failed

So I recommend using userbot/pyrogram instead of TG-Bot
Or add delayed release / failed retransmission

**Comment by y-young** [comment]
## Just a few notes here:
### Still using `python-telegram-bot`:
1. Wait when hitting flooding limit: blocks executing because this application is currently synchronous
2. Use MessageQueue: works but the usage of PTB's MQ is not so elegant, and they're considering refactoring it

### Use asynchronous Bot API frameworks:
1. [aiogram](https://github.com/aiogram/aiogram)

### Use asynchronous MtProto API frameworks:
- Pros:
  - More control
  - Direct connection to Telegram server means faster response
- Cons: 
  - Users will need to apply for Telegram API ID & Hash
  - Webhooks are not available
  - If we abandon Bot API, some features will be unavailable, such as InlineQuery, InlineKeyboard...
1. [Telethon](https://github.com/LonamiWebs/Telethon): seems that uploading documents is slow sometimes because of multiple chunks
2. [Pyrogram](https://github.com/pyrogram/pyrogram): network connection seems unstable on my side
